from __future__ import annotations

import argparse
import os
import pwd
import shutil
import sys
import time
import uuid
from pathlib import Path
from typing import Any, Optional

from .agent_bridge import notify_application
from .paths import config_dir, ensure_private_dir


COMMAND_LIMIT = 4096
VALUE_LIMIT = 4096
SUPPORTED_SHELLS = {"bash", "zsh", "fish"}


BASH_PROFILE = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
export HOME="$MUJTERM_ORIGINAL_HOME"
if [[ -r "$HOME/.bash_profile" ]]; then
    source "$HOME/.bash_profile"
elif [[ -r "$HOME/.bash_login" ]]; then
    source "$HOME/.bash_login"
elif [[ -r "$HOME/.profile" ]]; then
    source "$HOME/.profile"
fi
source "$MUJTERM_BASH_ROOT/integration.bash"
'''


BASH_INTEGRATION = r'''if [[ -n "${MUJTERM_TERMINAL_ID:-}" && -x "${MUJTERM_SHELL_HOOK:-}" && -z "${MUJTERM_BASH_INTEGRATED:-}" ]]; then
    export MUJTERM_BASH_INTEGRATED=1
    __mujterm_command_active=0
    __mujterm_in_hook=0
    __mujterm_in_prompt=1
    __mujterm_debug_owned=0
    __mujterm_last_status=0
    __mujterm_prompt_end=$'\e]133;B\a'

    __mujterm_preexec() {
        [[ $__mujterm_in_hook == 0 && $__mujterm_in_prompt == 0 && $__mujterm_command_active == 0 ]] || return 0
        __mujterm_in_hook=1
        __mujterm_command_active=1
        local command_text
        command_text="$(builtin fc -ln -1 2>/dev/null)"
        command_text="${command_text#"${command_text%%[![:space:]]*}"}"
        [[ -n "$command_text" ]] || command_text="$1"
        printf '\033]133;C\007'
        command "$MUJTERM_SHELL_HOOK" start --shell bash --cwd "$PWD" --command "$command_text"
        __mujterm_in_hook=0
        return 0
    }

    __mujterm_preexec_fallback() {
        local command_text
        command_text="$(builtin fc -ln -1 2>/dev/null)"
        command_text="${command_text#"${command_text%%[![:space:]]*}"}"
        printf '\033]133;C\007'
        command "$MUJTERM_SHELL_HOOK" start --shell bash --cwd "$PWD" --command "$command_text"
        return 0
    }

    __mujterm_precmd() {
        local command_status=$?
        __mujterm_last_status=$command_status
        __mujterm_in_prompt=1
        if [[ $__mujterm_command_active == 1 || $__mujterm_debug_owned == 0 ]]; then
            printf '\033]133;D;%s\007' "$command_status"
            command "$MUJTERM_SHELL_HOOK" end --shell bash --cwd "$PWD" --status "$command_status"
        fi
        __mujterm_command_active=0
        printf '\033]133;A\007'
        return "$command_status"
    }

    __mujterm_prompt_done() {
        case "$PS1" in
            *"$__mujterm_prompt_end"*) ;;
            *) PS1="${PS1}\[${__mujterm_prompt_end}\]" ;;
        esac
        __mujterm_in_prompt=0
        return "$__mujterm_last_status"
    }

    if declare -p PROMPT_COMMAND 2>/dev/null | command grep -q 'declare -a'; then
        PROMPT_COMMAND=(__mujterm_precmd "${PROMPT_COMMAND[@]}" __mujterm_prompt_done)
    elif [[ -n "${PROMPT_COMMAND:-}" ]]; then
        PROMPT_COMMAND=(__mujterm_precmd "$PROMPT_COMMAND" __mujterm_prompt_done)
    else
        PROMPT_COMMAND=(__mujterm_precmd __mujterm_prompt_done)
    fi

    if [[ -z "$(trap -p DEBUG)" ]]; then
        __mujterm_debug_owned=1
        trap '__mujterm_preexec "$BASH_COMMAND"' DEBUG
    else
        PS0="${PS0:-}"'$(__mujterm_preexec_fallback)'
    fi
fi
'''


ZSH_ENV = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
if [[ -n "${MUJTERM_ORIGINAL_ZDOTDIR:-}" && "$MUJTERM_ORIGINAL_ZDOTDIR" != "$MUJTERM_ZDOTDIR" && -r "$MUJTERM_ORIGINAL_ZDOTDIR/.zshenv" ]]; then
    ZDOTDIR="$MUJTERM_ORIGINAL_ZDOTDIR"
    source "$ZDOTDIR/.zshenv"
fi
export ZDOTDIR="$MUJTERM_ZDOTDIR"
'''


ZSH_RC = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
if [[ -n "${MUJTERM_ORIGINAL_ZDOTDIR:-}" && "$MUJTERM_ORIGINAL_ZDOTDIR" != "$MUJTERM_ZDOTDIR" && -r "$MUJTERM_ORIGINAL_ZDOTDIR/.zshrc" ]]; then
    ZDOTDIR="$MUJTERM_ORIGINAL_ZDOTDIR"
    source "$ZDOTDIR/.zshrc"
fi
export ZDOTDIR="$MUJTERM_ZDOTDIR"
source "$MUJTERM_ZDOTDIR/integration.zsh"
'''


ZSH_PROFILE = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
if [[ -n "${MUJTERM_ORIGINAL_ZDOTDIR:-}" && "$MUJTERM_ORIGINAL_ZDOTDIR" != "$MUJTERM_ZDOTDIR" && -r "$MUJTERM_ORIGINAL_ZDOTDIR/.zprofile" ]]; then
    ZDOTDIR="$MUJTERM_ORIGINAL_ZDOTDIR"
    source "$ZDOTDIR/.zprofile"
fi
export ZDOTDIR="$MUJTERM_ZDOTDIR"
'''


ZSH_LOGIN = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
if [[ -n "${MUJTERM_ORIGINAL_ZDOTDIR:-}" && "$MUJTERM_ORIGINAL_ZDOTDIR" != "$MUJTERM_ZDOTDIR" && -r "$MUJTERM_ORIGINAL_ZDOTDIR/.zlogin" ]]; then
    ZDOTDIR="$MUJTERM_ORIGINAL_ZDOTDIR"
    source "$ZDOTDIR/.zlogin"
fi
export ZDOTDIR="$MUJTERM_ZDOTDIR"
'''


ZSH_LOGOUT = r'''# Generated by MujTerm. User shell files are only sourced, never edited.
if [[ -n "${MUJTERM_ORIGINAL_ZDOTDIR:-}" && "$MUJTERM_ORIGINAL_ZDOTDIR" != "$MUJTERM_ZDOTDIR" && -r "$MUJTERM_ORIGINAL_ZDOTDIR/.zlogout" ]]; then
    ZDOTDIR="$MUJTERM_ORIGINAL_ZDOTDIR"
    source "$ZDOTDIR/.zlogout"
fi
export ZDOTDIR="$MUJTERM_ZDOTDIR"
'''


ZSH_INTEGRATION = r'''if [[ -n "${MUJTERM_TERMINAL_ID:-}" && -x "${MUJTERM_SHELL_HOOK:-}" && -z "${MUJTERM_ZSH_INTEGRATED:-}" ]]; then
    export MUJTERM_ZSH_INTEGRATED=1
    typeset -g __mujterm_command_active=0
    typeset -g __mujterm_last_status=0
    typeset -g __mujterm_prompt_end=$'\e]133;B\a'

    __mujterm_zsh_preexec() {
        local command_text="$1"
        __mujterm_command_active=1
        printf '\033]133;C\007'
        command "$MUJTERM_SHELL_HOOK" start --shell zsh --cwd "$PWD" --command "$command_text"
    }

    __mujterm_zsh_precmd() {
        local command_status=$?
        __mujterm_last_status=$command_status
        if (( __mujterm_command_active )); then
            printf '\033]133;D;%s\007' "$command_status"
            command "$MUJTERM_SHELL_HOOK" end --shell zsh --cwd "$PWD" --status "$command_status"
        fi
        __mujterm_command_active=0
        printf '\033]133;A\007'
        return "$command_status"
    }

    __mujterm_zsh_prompt_done() {
        if [[ "$PROMPT" != *"$__mujterm_prompt_end"* ]]; then
            PROMPT="${PROMPT}%{${__mujterm_prompt_end}%}"
        fi
        return "$__mujterm_last_status"
    }

    typeset -ga precmd_functions preexec_functions
    preexec_functions=(__mujterm_zsh_preexec ${preexec_functions:#__mujterm_zsh_preexec})
    precmd_functions=(__mujterm_zsh_precmd ${precmd_functions:#__mujterm_zsh_precmd} __mujterm_zsh_prompt_done)
fi
'''


FISH_INTEGRATION = r'''if set -q MUJTERM_TERMINAL_ID; and set -q MUJTERM_SHELL_HOOK; and not set -q MUJTERM_FISH_INTEGRATED
    set -gx MUJTERM_FISH_INTEGRATED 1
    set -g __mujterm_command_active 0
    functions -c fish_prompt __mujterm_original_fish_prompt

    function fish_prompt
        printf '\033]133;A\007'
        __mujterm_original_fish_prompt
        printf '\033]133;B\007'
    end

    function __mujterm_fish_preexec --on-event fish_preexec
        set -g __mujterm_command_active 1
        printf '\033]133;C\007'
        command $MUJTERM_SHELL_HOOK start --shell fish --cwd "$PWD" --command "$argv[1]"
    end

    function __mujterm_fish_postexec --on-event fish_postexec
        set -l command_status $status
        if test $__mujterm_command_active -eq 1
            printf '\033]133;D;%s\007' $command_status
            command $MUJTERM_SHELL_HOOK end --shell fish --cwd "$PWD" --status $command_status
        end
        set -g __mujterm_command_active 0
    end
end
'''


def valid_terminal_id(value: Optional[str]) -> bool:
    if not value:
        return False
    try:
        uuid.UUID(value)
        return True
    except ValueError:
        return False


def build_shell_event(
    event: str,
    terminal_id: str,
    shell: str,
    cwd: str,
    command: str = "",
    status: Optional[int] = None,
) -> Optional[dict[str, Any]]:
    if event not in {"start", "end"} or not valid_terminal_id(terminal_id):
        return None
    shell_name = Path(shell).name.lower()
    if shell_name not in SUPPORTED_SHELLS:
        return None
    clean_cwd = cwd.replace("\x00", "")[:VALUE_LIMIT]
    payload: dict[str, Any] = {
        "version": 1,
        "kind": "shell",
        "terminal_id": terminal_id,
        "event": f"command_{event}",
        "shell": shell_name,
        "cwd": clean_cwd,
        "timestamp": time.time(),
    }
    if event == "start":
        clean_command = command.replace("\x00", "").strip()[:COMMAND_LIMIT]
        if not clean_command:
            return None
        payload["command"] = clean_command
    else:
        if status is None or not 0 <= status <= 255:
            return None
        payload["status"] = status
    return payload


def emit_shell_event(
    event: str,
    shell: str,
    cwd: str,
    command: str = "",
    status: Optional[int] = None,
) -> int:
    terminal_id = os.environ.get("MUJTERM_TERMINAL_ID", "")
    if os.environ.get("MUJTERM_SHELL_INTEGRATION") != "1":
        return 0
    payload = build_shell_event(
        event, terminal_id, shell, cwd, command=command, status=status
    )
    if payload:
        notify_application(payload)
    return 0


def _write_if_changed(path: Path, content: str) -> None:
    if path.exists():
        try:
            if path.read_text(encoding="utf-8") == content:
                return
        except OSError:
            pass
    path.write_text(content, encoding="utf-8")
    path.chmod(0o600)


def write_shell_files(root: Optional[Path] = None) -> dict[str, Path]:
    target = ensure_private_dir(root or config_dir() / "shell")
    bash_root = ensure_private_dir(target / "bash")
    zsh_root = ensure_private_dir(target / "zsh")
    fish_init = target / "integration.fish"
    _write_if_changed(bash_root / ".bash_profile", BASH_PROFILE)
    _write_if_changed(bash_root / "integration.bash", BASH_INTEGRATION)
    _write_if_changed(zsh_root / ".zshenv", ZSH_ENV)
    _write_if_changed(zsh_root / ".zprofile", ZSH_PROFILE)
    _write_if_changed(zsh_root / ".zshrc", ZSH_RC)
    _write_if_changed(zsh_root / ".zlogin", ZSH_LOGIN)
    _write_if_changed(zsh_root / ".zlogout", ZSH_LOGOUT)
    _write_if_changed(zsh_root / "integration.zsh", ZSH_INTEGRATION)
    _write_if_changed(fish_init, FISH_INTEGRATION)
    return {"bash": bash_root, "zsh": zsh_root, "fish": fish_init}


def _default_shell() -> str:
    candidate = os.environ.get("SHELL", "")
    if candidate and Path(candidate).is_file():
        return candidate
    try:
        candidate = pwd.getpwuid(os.getuid()).pw_shell
    except KeyError:
        candidate = ""
    return candidate if candidate and Path(candidate).is_file() else "/bin/sh"


def _resolve_hook_command() -> str:
    development = Path(__file__).resolve().parents[2] / "bin" / "mujterm-shell-hook"
    if development.is_file():
        return str(development)
    return shutil.which("mujterm-shell-hook") or "mujterm-shell-hook"


def launch_shell() -> int:
    shell = _default_shell()
    shell_name = Path(shell).name.lower()
    environment = os.environ.copy()
    environment["MUJTERM_SHELL_INTEGRATION"] = "1"
    environment.setdefault("MUJTERM_SHELL_HOOK", _resolve_hook_command())
    files = write_shell_files()

    if shell_name == "bash":
        original_home = environment.get("MUJTERM_ORIGINAL_HOME") or str(Path.home())
        environment["MUJTERM_ORIGINAL_HOME"] = original_home
        environment["MUJTERM_BASH_ROOT"] = str(files["bash"])
        environment["HOME"] = str(files["bash"])
        arguments = [shell, "--login", "-i"]
    elif shell_name == "zsh":
        original = (
            environment.get("MUJTERM_ORIGINAL_ZDOTDIR")
            or environment.get("ZDOTDIR")
            or str(Path.home())
        )
        environment["MUJTERM_ORIGINAL_ZDOTDIR"] = original
        environment["MUJTERM_ZDOTDIR"] = str(files["zsh"])
        environment["ZDOTDIR"] = str(files["zsh"])
        arguments = [shell, "--login", "-i"]
    elif shell_name == "fish":
        arguments = [
            shell,
            "--login",
            "--init-command",
            f"source {files['fish']}",
            "-i",
        ]
    else:
        arguments = [f"-{shell_name}"]
    os.execvpe(shell, arguments, environment)
    return 127


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="mujterm-shell")
    subparsers = parser.add_subparsers(dest="action", required=True)
    subparsers.add_parser("launch")
    emit = subparsers.add_parser("emit")
    emit.add_argument("event", choices=("start", "end"))
    emit.add_argument("--shell", required=True)
    emit.add_argument("--cwd", required=True)
    emit.add_argument("--command", default="")
    emit.add_argument("--status", type=int)
    arguments = parser.parse_args(argv)
    if arguments.action == "launch":
        return launch_shell()
    return emit_shell_event(
        arguments.event,
        arguments.shell,
        arguments.cwd,
        command=arguments.command,
        status=arguments.status,
    )


def launch_main() -> int:
    return launch_shell()


def hook_main() -> int:
    return main(["emit", *sys.argv[1:]])


if __name__ == "__main__":
    raise SystemExit(main())
